USE myTalentBank;
GO
ALTER TABLE JobPosting WITH CHECK
ADD CONSTRAINT FK_JobID FOREIGN KEY(JobID) REFERENCES Jobs(ID)
ON UPDATE CASCADE
GO
ALTER TABLE JobPosting WITH CHECK
ADD CONSTRAINT FK_DeptID FOREIGN KEY(DeptID) REFERENCES Department(ID)
ON UPDATE CASCADE
GO
ALTER TABLE JobPosting WITH CHECK
ADD CONSTRAINT FK_HiringID FOREIGN KEY(HiringID) REFERENCES HiringTeam(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Applicant
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE CASCADE
GO
/*ALTER TABLE AvailableJobs
ADD CONSTRAINT FK_ApplicantAvailablejJobs FOREIGN KEY(ApplicantID) REFERENCES Applicant (ID)
ON UPDATE CASCADE*/
GO
ALTER TABLE JobPosting
ADD CONSTRAINT FK_JobPostingJobs FOREIGN KEY(AvailableJobsID) REFERENCES AvailableJobs(ID)
ON UPDATE CASCADE
GO